---
services:
  ibkr:
    image: ghcr.io/extrange/ibkr:latest #latest, stable, 10.21, 10.21.1p etc
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:8888:8888" # API access
    ulimits:
      nofile: 10000 # See FAQ
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: gateway
      #
      # Variables prefixed with IBC_ override IBCAlpha`s config.ini:
      IBC_TradingMode: 'paper' #live
      IBC_ReadOnlyApi: 'no'
      IBC_AcceptNonBrokerageAccountWarning: 'yes'
      IBC_AcceptIncomingConnectionAction: 'accept'
      # ...
      # See below for more details
